import { createTraktClient } from "./trakt.js";

const asset=path=>`${import.meta.env.BASE_URL}${path}`;
const catalog=[
{id:"lanterns",title:"Lanterns",type:"Dizi",year:2026,extra:"1 Sezon",certificate:"18+",poster:asset("posters/lanterns.jpg"),match:96,tagline:"Kozmik bir suç. Dünyaya ait karanlık bir sır.",summary:"Yeni üye John Stewart ve efsanevi Lantern Hal Jordan, Amerika'nın kalbinde işlenen bir cinayeti araştırırken kendilerini hem dünyayı hem de birliklerini sarsacak bir komplonun içinde bulur.",genres:["Suç","Gizem","Bilim Kurgu","Dram"],imdb:"—",imdbNote:"Yeni dizi",rtCritic:"94%",rtAudience:"83%",trailer:"https://www.youtube.com/watch?v=XmcIjxwLJcY",moods:["dark","tense","epic"]},
{id:"the-batman",title:"The Batman",type:"Film",year:2022,extra:"2s 56dk",certificate:"13+",poster:asset("posters/the-batman.jpg"),match:93,tagline:"Korku bir araçtır. Gerçek ise daha karanlık.",summary:"Batman, Gotham'ın seçkinlerini hedef alan bir katilin bıraktığı şifreleri takip ederken şehrin geçmişine uzanan büyük bir yozlaşmayı açığa çıkarır.",genres:["Suç","Gizem","Gerilim"],imdbId:"tt1877830",imdb:"7.8",imdbNote:"IMDb puanı",rtCritic:"85%",rtAudience:"87%",trailer:"https://www.youtube.com/watch?v=mqqft2x_Aa4",moods:["dark","tense"]},
{id:"arrival",title:"Arrival",type:"Film",year:2016,extra:"1s 56dk",certificate:"13+",poster:asset("posters/arrival.jpg"),match:91,tagline:"İletişim kurmak, zamanı değiştirebilir.",summary:"Dünyanın farklı noktalarına gizemli uzay araçları indiğinde bir dilbilimci, ziyaretçilerin niyetini çözmek için zamana karşı yarışır.",genres:["Bilim Kurgu","Gizem","Dram"],imdbId:"tt2543164",imdb:"7.9",imdbNote:"IMDb puanı",rtCritic:"94%",rtAudience:"82%",trailer:"https://www.youtube.com/watch?v=tFMo3UJ4B4g",moods:["thoughtful","epic"]},
{id:"prisoners",title:"Prisoners",type:"Film",year:2013,extra:"2s 33dk",certificate:"18+",poster:asset("posters/prisoners.jpg"),match:89,tagline:"Bir baba ne kadar ileri gidebilir?",summary:"Kızı kaybolan bir baba, soruşturmadan sonuç çıkmayınca adaleti kendi ellerine alır ve ahlaki sınırları geri dönülmez biçimde aşar.",genres:["Suç","Gizem","Gerilim"],imdbId:"tt1392214",imdb:"8.2",imdbNote:"IMDb puanı",rtCritic:"81%",rtAudience:"87%",trailer:"https://www.youtube.com/watch?v=bpXfcTF6iVk",moods:["dark","tense"]},
{id:"blade-runner",title:"Blade Runner 2049",type:"Film",year:2017,extra:"2s 44dk",certificate:"15+",poster:asset("posters/blade-runner-2049.jpg"),match:88,tagline:"İnsan olmak ne demek?",summary:"Genç bir blade runner, toplumdan geriye kalanları kaosa sürükleyebilecek eski bir sırrı keşfeder ve yıllardır kayıp olan Rick Deckard'ı aramaya koyulur.",genres:["Bilim Kurgu","Gizem","Dram"],imdbId:"tt1856101",imdb:"8.0",imdbNote:"IMDb puanı",rtCritic:"88%",rtAudience:"88%",trailer:"https://www.youtube.com/watch?v=gCcx85zbxz4",moods:["dark","thoughtful","epic"]},
{id:"watchmen",title:"Watchmen",type:"Film",year:2009,extra:"2s 43dk",certificate:"18+",poster:asset("posters/watchmen.jpg"),match:86,tagline:"Bizi kim gözetleyecek?",summary:"Alternatif bir 1985'te emekli bir kahramanın öldürülmesi, eski takım arkadaşlarını insanlığın kaderine uzanan karanlık bir komployla yüzleştirir.",genres:["Gizem","Aksiyon","Bilim Kurgu"],imdbId:"tt0409459",imdb:"7.6",imdbNote:"IMDb puanı",rtCritic:"65%",rtAudience:"71%",trailer:"https://www.youtube.com/watch?v=wdiHDzT6YbQ",moods:["dark","epic"]}
];
const regions={
TR:{flag:"🇹🇷",name:"Türkiye",offers:[{provider:"HBO Max",cls:"max",logo:"HBO\nMAX",plan:"Standart • 1080p",price:"229,90 TL",cadence:"/ ay",best:true},{provider:"Hepsiburada",cls:"hb",logo:"hepsi\nburada",plan:"Premium'a reklamlı dahil",price:"Paket dahil",cadence:"fiyatı doğrula"}],best:"HBO Max Standart ile doğrudan izle"},
US:{flag:"🇺🇸",name:"Amerika",offers:[{provider:"HBO Max",cls:"max",logo:"HBO\nMAX",plan:"Basic with ads",price:"$9.99",cadence:"/ month",best:true}],best:"HBO Max Basic is the lowest plan"},
GB:{flag:"🇬🇧",name:"Birleşik Krallık",offers:[{provider:"HBO Max",cls:"max",logo:"HBO\nMAX",plan:"Basic with ads",price:"£5.99",cadence:"/ month",best:true},{provider:"NOW",cls:"now",logo:"NOW",plan:"Entertainment + HBO Max",price:"£9.99",cadence:"/ month"}],best:"HBO Max Basic is the lowest plan"},
DE:{flag:"🇩🇪",name:"Almanya",offers:[{provider:"HBO Max",cls:"max",logo:"HBO\nMAX",plan:"Basis mit Werbung",price:"Preis prüfen",cadence:"live data pending",best:true},{provider:"WOW",cls:"wow",logo:"WOW",plan:"Serien",price:"Preis prüfen",cadence:"live data pending"}],best:"Canlı fiyat bağlantısı gerekli"}
};
const $=s=>document.querySelector(s);const state={current:catalog[0],region:localStorage.getItem("seyir-region")||"TR",watched:new Set(JSON.parse(localStorage.getItem("seyir-watched")||"[]")),saved:new Set(JSON.parse(localStorage.getItem("seyir-saved")||"[]")),mood:"dark",traktProfile:null};
const trakt=createTraktClient({clientId:import.meta.env.VITE_TRAKT_CLIENT_ID,authBaseUrl:import.meta.env.VITE_TRAKT_AUTH_URL,redirectUri:`${window.location.origin}${import.meta.env.BASE_URL}`});
function persist(){localStorage.setItem("seyir-watched",JSON.stringify([...state.watched]));localStorage.setItem("seyir-saved",JSON.stringify([...state.saved]));localStorage.setItem("seyir-region",state.region)}
function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2200)}
function renderOffers(){const region=regions[state.region];$("#regionFlag").textContent=region.flag;$("#regionName").textContent=region.name;$("#availabilityTitle").textContent=`${region.name}'de izlenebilir`;$("#offers").innerHTML=region.offers.map(offer=>`<div class="offer ${offer.best?"best":""}"><div class="provider-logo ${offer.cls}">${offer.logo.replace("\n","<br>")}</div><div class="offer-copy"><strong>${offer.provider}</strong><small>${offer.plan}</small>${offer.best?'<span class="tag">En uygun</span>':""}</div><div class="offer-price"><strong>${offer.price}</strong><small>${offer.cadence}</small></div></div>`).join("");$("#bestText").textContent=region.best}
function renderRecommendations(){const filtered=catalog.filter(i=>i.id!==state.current.id).sort((a,b)=>(b.moods.includes(state.mood)?1:0)-(a.moods.includes(state.mood)?1:0)||b.match-a.match).slice(0,5);$("#recommendationGrid").innerHTML=filtered.map(item=>`<button class="recommendation-card ${state.watched.has(item.id)?"watched":""}" data-id="${item.id}" type="button"><img src="${item.poster}" alt="${item.title} posteri" loading="lazy"/><span class="recommendation-copy"><strong>${item.title}</strong><small>${item.year} • ${item.type}</small><span class="why">%${item.match} eşleşme · ${item.genres[0]}</span></span></button>`).join("");$("#recommendationGrid").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>selectTitle(b.dataset.id)));$(".section-heading h3").textContent=`${state.current.title} hoşuna gittiyse`}
function renderActions(){const watched=state.watched.has(state.current.id),saved=state.saved.has(state.current.id);$("#watchedButton").classList.toggle("selected",watched);$("#watchedButton").innerHTML=watched?"<span>✓</span> İzlendi":"<span>✓</span> İzledim";$("#saveButton").classList.toggle("selected",saved);$("#saveButton").innerHTML=saved?"<span>✓</span> Listemde":"<span>＋</span> Listeme ekle";$("#watchlistCount").textContent=state.saved.size}
function selectTitle(id){const item=catalog.find(e=>e.id===id);if(!item)return;state.current=item;const poster=$("#poster");poster.classList.add("swap");setTimeout(()=>{poster.src=item.poster;poster.alt=`${item.title} posteri`;poster.classList.remove("swap")},160);$("#detailBackdrop").style.backgroundImage=`url('${item.poster}')`;$("#meta").innerHTML=`${item.type.toUpperCase()} <span>•</span> ${item.year} <span>•</span> ${item.extra.toUpperCase()} <span>•</span> ${item.certificate}`;$("#title").textContent=item.title;$("#tagline").textContent=item.tagline;$("#summary").textContent=item.summary;$("#genres").innerHTML=item.genres.map(g=>`<span>${g}</span>`).join("");$("#imdbRating").textContent=item.imdb;$(".imdb small").textContent=item.imdbNote;$("#rtCritic").textContent=item.rtCritic;$("#rtAudience").textContent=item.rtAudience;$("#matchBadge").textContent=`%${item.match} eşleşme`;$("#trailerButton").href=item.trailer;$("#searchInput").value=item.title;$("#searchResults").hidden=true;renderActions();renderRecommendations();if(id!=="lanterns")document.querySelector(".detail-card").scrollIntoView({behavior:"smooth",block:"center"})}
function renderSearch(query){const n=query.trim().toLocaleLowerCase("tr"),results=catalog.filter(i=>i.title.toLocaleLowerCase("tr").includes(n)).slice(0,5),box=$("#searchResults");if(!n||!results.length){box.hidden=true;return}box.innerHTML=results.map(i=>`<button class="search-result" data-id="${i.id}" type="button"><img src="${i.poster}" alt=""/><span><strong>${i.title}</strong><small>${i.type} • ${i.year}</small></span></button>`).join("");box.hidden=false;box.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>selectTitle(b.dataset.id)))}
$("#searchInput").addEventListener("input",e=>renderSearch(e.target.value));$("#searchInput").addEventListener("keydown",e=>{if(e.key==="Enter"){const first=catalog.find(i=>i.title.toLocaleLowerCase("tr").includes(e.target.value.toLocaleLowerCase("tr")));if(first)selectTitle(first.id)}if(e.key==="Escape")$("#searchResults").hidden=true});document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#searchInput").focus();$("#searchInput").select()}});document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap"))$("#searchResults").hidden=true;if(!e.target.closest(".region-picker")){$("#regionMenu").hidden=true;$("#regionButton").setAttribute("aria-expanded","false")}});
$("#regionButton").addEventListener("click",()=>{const m=$("#regionMenu");m.hidden=!m.hidden;$("#regionButton").setAttribute("aria-expanded",String(!m.hidden))});$("#regionMenu").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{state.region=b.dataset.region;persist();renderOffers();$("#regionMenu").hidden=true;showToast(`${regions[state.region].name} bölgesine geçildi`)}));$(".quick-tags").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{$("#searchInput").value=b.dataset.query;renderSearch(b.dataset.query)}));
$("#watchedButton").addEventListener("click",async()=>{const item=state.current,id=item.id,watched=!state.watched.has(id);watched?state.watched.add(id):state.watched.delete(id);persist();renderActions();renderRecommendations();showToast(watched?"İzlendi olarak işaretlendi":"İzlendi işareti kaldırıldı");if(trakt.isConnected()){try{const synced=await trakt.setMovieWatched(item,watched);if(synced)showToast("İzlendi durumu Trakt ile eşitlendi")}catch(error){showToast(error.message)}}});$("#saveButton").addEventListener("click",async()=>{const item=state.current,id=item.id,saved=!state.saved.has(id);saved?state.saved.add(id):state.saved.delete(id);persist();renderActions();showToast(saved?"Listene eklendi":"Listenden çıkarıldı");if(trakt.isConnected()){try{const synced=await trakt.setWatchlist(item,saved);if(synced)showToast("Listen Trakt ile eşitlendi")}catch(error){showToast(error.message)}}});$("#alertButton").addEventListener("click",e=>{e.currentTarget.classList.toggle("active");showToast(e.currentTarget.classList.contains("active")?"Fiyat alarmı kuruldu":"Fiyat alarmı kapatıldı")});$("#watchlistNav").addEventListener("click",()=>showToast(state.saved.size?`Listende ${state.saved.size} içerik var`:"Listen henüz boş"));
$("#moodButton").addEventListener("click",()=>{$("#moodBar").hidden=!$("#moodBar").hidden});$("#moodBar").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{state.mood=b.dataset.mood;$("#moodBar").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));renderRecommendations()}));
const modal=$("#traktModal"),traktConnectButton=$("#traktConnectButton"),traktDisconnectButton=$("#traktDisconnectButton"),traktStatus=$("#traktStatus");
function setTraktStatus(message,type="info"){traktStatus.textContent=message;traktStatus.dataset.type=type;traktStatus.hidden=!message}
function renderTraktConnection(){const connected=trakt.isConnected();$("#traktButton").innerHTML=`<span class="trakt-dot"></span> ${connected?(state.traktProfile?.user?.name||state.traktProfile?.user?.username||"Trakt bağlı"):"Trakt'ı bağla"}`;traktConnectButton.hidden=connected;traktDisconnectButton.hidden=!connected;if(connected){$("#traktTitle").textContent="Trakt hesabın bağlı";$("#traktDescription").textContent="Geçmişin ve izleme listen Seyir önerilerine uygulanıyor.";$("#traktHelp").textContent="Bağlantıyı kaldırırsan cihazdaki Seyir listen korunur.";setTraktStatus(state.traktProfile?"Eşitleme tamamlandı.":"Trakt oturumu hazır.","success");return}$("#traktTitle").textContent="Trakt geçmişini Seyir'e bağla";$("#traktDescription").textContent="İzlediklerin önerilerden otomatik çıkarılır, yeni izlediklerin tek dokunuşla Trakt'a işlenir.";if(!trakt.configured){traktConnectButton.disabled=true;$("#traktHelp").textContent="Yönetici kurulumu gerekiyor: OAuth Worker adresi ve Trakt Client ID tanımlanmamış.";setTraktStatus("Trakt bağlantısı henüz yapılandırılmadı.","warning")}else{traktConnectButton.disabled=false;$("#traktHelp").textContent="Trakt'ın güvenli giriş ekranına yönlendirileceksiniz.";setTraktStatus("")}}
async function syncTraktAccount(){setTraktStatus("Trakt geçmişi ve listeleri eşitleniyor…");const [profile,sync]=await Promise.all([trakt.getProfile(),trakt.getSyncState()]);state.traktProfile=profile;for(const item of catalog){if(item.imdbId&&sync.watchedImdb.has(item.imdbId))state.watched.add(item.id);if(item.imdbId&&sync.savedImdb.has(item.imdbId))state.saved.add(item.id)}persist();renderActions();renderRecommendations();renderTraktConnection()}
$("#traktButton").addEventListener("click",()=>{renderTraktConnection();modal.hidden=false});$("#modalClose").addEventListener("click",()=>modal.hidden=true);modal.addEventListener("click",e=>{if(e.target===modal)modal.hidden=true});traktConnectButton.addEventListener("click",()=>{try{trakt.beginAuthorization()}catch(error){setTraktStatus(error.message,"warning")}});traktDisconnectButton.addEventListener("click",()=>{trakt.disconnect();state.traktProfile=null;renderTraktConnection();showToast("Trakt bağlantısı kaldırıldı")});
$("#detailBackdrop").style.backgroundImage=`url('${state.current.poster}')`;selectTitle(state.current.id);renderOffers();renderTraktConnection();
(async()=>{try{const result=await trakt.finishAuthorizationFromUrl();if(result.handled){modal.hidden=false;await syncTraktAccount();showToast("Trakt hesabın bağlandı")}else if(trakt.isConnected()){await syncTraktAccount()}}catch(error){modal.hidden=false;setTraktStatus(error.message,"error");showToast("Trakt bağlantısı tamamlanamadı")}})();
